name: php_syntax-test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.1
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres_test
          POSTGRES_USER: db_user
          POSTGRES_PASSWORD: db_password
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      APP_ENV: testing
      DB_HOST: localhost
      DB_PORT: 5432
      PAGER: cat # prevent psql commands using less
    steps:
      # build(for syntax and test)
      - uses: actions/checkout@v2
      - name: fetch all history for git log in syntax shells and on outputing npm run hash source
        run: git fetch --prune --unshallow
      - name: set up php 7.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3.x
      - name: composer install
        run: composer install
        working-directory: /home/runner/work/qoo-cheese/qoo-cheese/yeahcheese
      - name: Generate key
        run: php artisan key:generate
        working-directory: /home/runner/work/qoo-cheese/qoo-cheese/yeahcheese
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: /home/runner/work/qoo-cheese/qoo-cheese/yeahcheese

      # syntax
      - name: install reviewdog
        run: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b tmp/bin
      - name: check syntax(php)
        run: ./yeahcheese/syntax/php_check.sh
