name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - name: copy package.json
        run: cp yeahcheese/package.json package.json
        working-directory: /home/runner/work/qoo-cheese/qoo-cheese/
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'yeahcheese/resources/js'