name: reviewdog

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  eslint:

    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        working-directory: /home/runner/work/qoo-cheese/qoo-cheese/yeahcheese
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'yeahcheese/resources/js/**.{js,ts,tsx,vue}'